### ISSUE TITLE
Fejl i data på dashboard

### ISSUE THREAD

**Issue by EditorLabsRW** [EditorLabsRW/Dashboards#11]
Data ser helt skævt ud på dashboard

**Comment by mortenanders** [comment]
Uddyb?

![2016-06-27_11h57_03](https://cloud.githubusercontent.com/assets/3471334/16375950/4beca2b6-3c5e-11e6-9b2a-4a0f4f335951.png)

**Comment by EditorLabsRW** [comment]
![dash](https://cloud.githubusercontent.com/assets/20075518/16378354/be5ebcdc-3c6b-11e6-9e79-7a49f3e3fdbb.png)

1 og 2) jeg tror data er forskudt 2-3 timer? Kan det være noget med tidszone?
1) Det virker helt forkert, at trafikken styrtdykker kl. 22. 
2a) Når jeg tjekker for faktiske udgivelser på Tipsbladet, passer det ikke med de grafer vi gør op. Der udkommer eks. ikke artikler før kl 6. 
3) Fjern henvisning til Chartbeat

Derudover:
- Gennemsnit antal artikler fra tidligere dage bør være en float i stedet for et helt tal. 
- Graf for pageviews og artikler for samme dag skal være samme farve. Dvs. fra i dag er grøn, gennemsnit blå (eksempelvis)
- Som vist på min graf vil det være fint, hvis igangværende graf er stiplet

**Comment by mortenanders** [comment]
1-2) Det kigger jeg på
3) Det er ikke til chartbeat, men til grafmotoren. Den kan ikke fjernes. Man kan dog ændre positionen.

Ad1) Hvor mange decimaler?
Ad2) Ok
Ad3) Ok

![2016-06-27_14h12_42](https://cloud.githubusercontent.com/assets/3471334/16379352/768e41a6-3c71-11e6-9916-81d178b1e3ae.png)

**Comment by mortenanders** [comment]
Det er helt sikkert tidszonen der spiller ind. Det ser ud til at elastic laver histogrammet baseret på UTC, hvilket er helt forventeligt. Jeg forestiller mig at vi bliver nødt til at ligge en tidszone som en del profilen, således at det kan matche hvorend man er i verdenen og iøvrigt også den man har sat på sin GA. Enig? @EditorLabsRW

**Comment by EditorLabsRW** [comment]
AD) 1 decimal

Angående tidszone: Enig.
