### ISSUE TITLE
Farver på Dashboard graf

### ISSUE THREAD

**Issue by EditorLabsRW** [EditorLabsRW/Dashboards#13]
Pageviews og Articles fra samme dag i grøn
P og A gennemsnit i gul

**Comment by mortenanders** [comment]
Skiftede til grøn- og gulagtigt fra themet.

![2016-06-30_15h05_58](https://cloud.githubusercontent.com/assets/3471334/16489104/2e63baea-3ed4-11e6-9744-06c0d3b69e10.png)
