### ISSUE TITLE
Farver på entrance/exit

### ISSUE THREAD

**Issue by EditorLabsRW** [EditorLabsRW/Dashboards#14]
Farve på entrance = grøn
Farve på exit = rød

Derudover skal der være transparency/opacity så de ikke fuldstændigt kan skjule for hinanden

**Comment by mortenanders** [comment]
@EditorLabsRW Det har jeg rettet til nu, men opacity er lidt svær at se, da entrances altid er inde i exits. På det gamle site havde vi også fill på pageviews, hvorfor opacity ofter bleve relevant - skal vi også have det her?
