### ISSUE TITLE
Sorter på metrics

### ISSUE THREAD

**Issue by EditorLabsRW** [EditorLabsRW/Dashboards#4]
Man skal kunne sortere på metrics i lister

**Comment by mortenanders** [comment]
Vi har en udfordring med at søge på TimeOnPage/Pageviews, da det er en beregnet værdi

**Comment by EditorLabsRW** [comment]
Ok - i første omgang vil det være fint at kunne sortere på alle de andre metrics.

**Comment by mortenanders** [comment]
@EditorLabsRW Er lagt på Artikellisten indtil videre. Jeg har iøvrigt glemt at det som jeg skrev om time on page også er gældende for exits og entrances, da det jo også er en beregning.

**Comment by mortenanders** [comment]
![2016-06-30_23h57_49](https://cloud.githubusercontent.com/assets/3471334/16505698/85616a8c-3f1e-11e6-89b5-65f428a8299d.png)

**Comment by mortenanders** [comment]
@EditorLabsRW - review lige, før jeg ligger det på de andre lister.

**Comment by EditorLabsRW** [comment]
Det ser godt ud - godkendt
