### ISSUE TITLE
Remember login

### ISSUE THREAD

**Issue by EditorLabsRW** [EditorLabsRW/Dashboards#7]
Gem login 30 dage, så der ikke skal logges ind ved hver session

**Comment by mortenanders** [comment]
Den lette løsning. Forlænge levetiden af token fra 1 time til 30 dage. Den rigtige løsning er at implementere refresh tolkens.

![2016-06-23_22h13_42](https://cloud.githubusercontent.com/assets/3471334/16318597/24a786ec-3990-11e6-9851-956eca8ff747.png)
